server:
  port: 8080
logging:
  file:
    path: '/logs'
  level:
    root: 'info'
spring:
  session:
    jdbc:
      initialize-schema: always
  thymeleaf:
    prefix: 'classpath:/templates/'
    suffix: '.html'
  datasource:
    url: 'jdbc:mysql://localhost:3306/drforest?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC'
    username: 'root'
    password: '1111'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: 'org.hibernate.dialect.MySQL5Dialect'
    generate-ddl: true
    hibernate:
      ddl-auto: update